fix/patch: added proper README files for all packages

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,23 +1,30 @@
 echo "Running pre-commit checks..."
 
-echo "\n[1/3] Running lint-staged..."
+echo "\n[1/4] Running lint-staged..."
 npx lint-staged
 if [ $? -ne 0 ]; then
   echo "\nlint-staged failed. Aborting commit."
   exit 1
 fi
 
-echo "\n[2/3] Running type-checking on changed packages..."
+echo "\n[2/4] Running type-checking on changed packages..."
 yarn run typecheck:changed
 if [ $? -ne 0 ]; then
   echo "\nType-checking failed. Aborting commit."
   exit 1
 fi
 
-echo "\n[3/3] Running tests on changed packages..."
+echo "\n[3/4] Running tests on changed packages..."
 yarn run test:changed
 if [ $? -ne 0 ]; then
   echo "\nTests failed. Aborting commit."
+  exit 1
+fi
+
+echo "\n[4/4] Generating documentation for changed packages..."
+yarn run generate-readme:changed
+if [ $? -ne 0 ]; then
+  echo "\nDocumentation generation failed. Aborting commit."
   exit 1
 fi
 
